.\" Copyright (C) 2009, 2016 Massimo Loschi <ccfedevel@gmail.com>
.\"
.\" This is is free documentation; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this manual; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.\"
.TH "CCFE HELP" 5 "September,  4 2016" "ccfe 1.58" "Curses Command Front-end"
.SH NAME
ccfe help \- the Curses Command Front-end contextual help configuration
.SH DESCRIPTION
The Curses Command Front-end menu is a tool which permits to collect scripts
or CCFE forms in hierarchical menus.

.B
Not yet implemented!!!

.SH SEE ALSO
.BR ccfe (1),
.BR ccfe.conf (5),
.BR ccfe_form (5),
.BR ccfe_menu (5),
.BR curses (3X),
.BR menu (3X)
.SH BUGS
Many cosmetics, but the tool is stable and usable.

.SH AUTHOR
Massimo Loschi <\fIccfedevel@gmail.com\fR>
